MOUSE_ENABLE = no # Mouse keys enabled.
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = yes
RGB_MATRIX_DRIVER = WS2812

TAP_DANCE_ENABLE = yes

EXTRAFLAGS += -flto