name: Build Corne Keyboard Custom Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-python@v1
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: git clone https://github.com/qmk/qmk_firmware.git
      - name: Install QMK Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc unzip wget zip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          sudo apt-get -y install git python3-pip python3-testresources
      - name: Install QMK
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes
      - name: Create Keymap Directory
        run: ln -s $(pwd) $HOME/qmk_firmware/keyboards/crkbd/keymaps/tavobarrientos
      - name: Compile Firmware
        run: qmk compile -kb crkbd/rev1 -km tavobarrientos
      - name: Move hex file to home
        run: mv $HOME/qmk_firmware/crkbd_rev1_tavobarrientos.hex $(pwd)
      - name: Publish the Artifact to Github Releases
        uses: actions/upload-artifact@v2
        with:
          name: Tavobarrientos Corne Custom Keymap
          path: crkbd_rev1_tavobarrientos.hex
      - name: Tagged Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'regs/tags/')
        with:
          files: |
            crkbd_rev1_tavobarrientos.hex
        
